In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline
import matplotlib
matplotlib.rcParams['figure.figsize']=(20,10)

In [2]:
df1=pd.read_csv("Heart_disease_details.csv")
df1.head(4)

,Name,Gender,Age,Chest pain,Shortness of breath,Fatigue,Systolic,Diastolic,Heart rate (bpm),Lung sounds,...,Cardiac CT,Obesity,Murmur,Chest x-ray,Previous illnesses,Pulmonary function tests,Spirometry,Diagnosis,Medications,Treatment
0,Jane Doe,Female,55,1,1,1,140,90,100,1,...,Shows a 50% blockage in the left anterior desc...,0,1,None,None,None,None,Coronary artery disease (CAD),"Aspirin, metoprolol, atorvastatin","Angioplasty,Coronary artery bypass surgery"
1,Mark Johnson,Male,57,1,1,1,150,80,110,1,...,Shows a 60% blockage in the right coronary artery,0,1,None,None,None,None,Coronary artery disease (CAD),"Aspirin, ramipril, atorvastatin","Angioplasty,Coronary artery bypass surgery"
2,Emily Davis,Female,60,1,1,1,130,85,95,1,...,Shows a 75% blockage in the left anterior desc...,0,1,None,None,None,None,Coronary artery disease (CAD),"Aspirin, lisinopril, rosuvastatin","Angioplasty,Coronary artery bypass surgery"
3,William Thompson,Male,62,1,1,1,145,90,100,1,...,Shows a 80% blockage in the left circumflex co...,0,1,None,None,None,None,Coronary artery disease (CAD),"Aspirin, metoprolol, atorvastatin","Angioplasty,Coronary artery bypass surgery"

In [3]:
df2=df1[['Gender','Age', 'Chest pain', 'Shortness of breath','Systolic', 'Diastolic', 
        'Heart rate (bpm)', 'Cholesterol level (mg/dL)','Cardiac CT', 'Diabetes', 'Hypertension', 'Smoking', 
         'Obesity','Previous illnesses','Diagnosis','Treatment']]

In [4]:
# rankings_pd.rename(columns = {'test':'TEST'}, inplace = True)
df3=df2.rename(columns={'Chest pain':'Chest_pain','Shortness of breath':'Shortness_of_breath',
                        'Heart rate (bpm)':'Heart_rate',
                        'Cardiac CT':'Cardiac_CT',
                       'Cholesterol level (mg/dL)':'Cholesterol_level',
                       'Previous illnesses':'Previous_illnesses'})

In [5]:
df3.describe()

,Age,Chest_pain,Shortness_of_breath,Systolic,Diastolic,Heart_rate,Cholesterol_level,Diabetes,Hypertension,Smoking,Obesity
count,334.000000,334.000000,334.000000,334.000000,334.000000,334.000000,334.000000,334.000000,334.000000,334.000000,334.000000
mean,50.149701,0.880240,0.826347,133.098802,83.203593,101.152695,213.637725,0.002994,0.553892,0.350299,0.056886
std,15.151935,0.325168,0.379379,10.040121,6.947282,11.667466,26.169645,0.054718,0.497833,0.477779,0.231973
min,23.000000,0.000000,0.000000,110.000000,70.000000,60.000000,150.000000,0.000000,0.000000,0.000000,0.000000
25%,40.000000,1.000000,1.000000,130.000000,80.000000,96.250000,200.000000,0.000000,0.000000,0.000000,0.000000
50%,50.000000,1.000000,1.000000,130.000000,80.000000,100.000000,210.000000,0.000000,1.000000,0.000000,0.000000
75%,61.500000,1.000000,1.000000,140.000000,90.000000,110.000000,230.000000,0.000000,1.000000,1.000000,0.000000
max,100.000000,1.000000,1.000000,160.000000,110.000000,120.000000,310.000000,1.000000,1.000000,1.000000,1.000000

In [7]:
dummies=pd.get_dummies(df3.Gender)
dummies.head(5)

   Female  Male
0       1     0
1       0     1
2       1     0
3       0     1
4       1     0

In [8]:
dummies=pd.get_dummies(df3.Gender)
dummies.head(5)

   Female  Male
0       1     0
1       0     1
2       1     0
3       0     1
4       1     0

In [9]:
# if female then it is going to be 1 else 0 for male
df4=pd.concat([df3.drop('Gender',axis='columns'),dummies.drop('Male',axis='columns')],axis='columns')
df4.head(2)

,Age,Chest_pain,Shortness_of_breath,Systolic,Diastolic,Heart_rate,Cholesterol_level,Cardiac_CT,Diabetes,Hypertension,Smoking,Obesity,Previous_illnesses,Diagnosis,Treatment,Female
0,55,1,1,140,90,100,220,Shows a 50% blockage in the left anterior desc...,0,1,1,0,None,Coronary artery disease (CAD),"Angioplasty,Coronary artery bypass surgery",1
1,57,1,1,150,80,110,210,Shows a 60% blockage in the right coronary artery,0,1,1,0,None,Coronary artery disease (CAD),"Angioplasty,Coronary artery bypass surgery",0

In [10]:
df5=df4.rename(columns={'Female':'Gender'})
df5.head(2)

,Age,Chest_pain,Shortness_of_breath,Systolic,Diastolic,Heart_rate,Cholesterol_level,Cardiac_CT,Diabetes,Hypertension,Smoking,Obesity,Previous_illnesses,Diagnosis,Treatment,Gender
0,55,1,1,140,90,100,220,Shows a 50% blockage in the left anterior desc...,0,1,1,0,None,Coronary artery disease (CAD),"Angioplasty,Coronary artery bypass surgery",1
1,57,1,1,150,80,110,210,Shows a 60% blockage in the right coronary artery,0,1,1,0,None,Coronary artery disease (CAD),"Angioplasty,Coronary artery bypass surgery",0

In [11]:
df5['Cardiac_CT']=df5['Cardiac_CT'].str.lower()

In [12]:
# df['fruits'] = df['fruits'].str.replace('apple', '')
df5['Cardiac_CT']=df5['Cardiac_CT'].str.replace('shows a','')

In [13]:
df5.head(4)

,Age,Chest_pain,Shortness_of_breath,Systolic,Diastolic,Heart_rate,Cholesterol_level,Cardiac_CT,Diabetes,Hypertension,Smoking,Obesity,Previous_illnesses,Diagnosis,Treatment,Gender
0,55,1,1,140,90,100,220,50% blockage in the left anterior descending ...,0,1,1,0,None,Coronary artery disease (CAD),"Angioplasty,Coronary artery bypass surgery",1
1,57,1,1,150,80,110,210,60% blockage in the right coronary artery,0,1,1,0,None,Coronary artery disease (CAD),"Angioplasty,Coronary artery bypass surgery",0
2,60,1,1,130,85,95,230,75% blockage in the left anterior descending ...,0,1,1,0,None,Coronary artery disease (CAD),"Angioplasty,Coronary artery bypass surgery",1
3,62,1,1,145,90,100,240,80% blockage in the left circumflex coronary ...,0,1,1,0,None,Coronary artery disease (CAD),"Angioplasty,Coronary artery bypass surgery",0

In [14]:
df5['Diagnosis']=df5['Diagnosis'].str.lower()

In [15]:
df5['Treatment']=df5['Treatment'].str.lower()

In [16]:
df5['Previous_illnesses']=df5['Previous_illnesses'].str.lower()

In [17]:
df5.head(4)

,Age,Chest_pain,Shortness_of_breath,Systolic,Diastolic,Heart_rate,Cholesterol_level,Cardiac_CT,Diabetes,Hypertension,Smoking,Obesity,Previous_illnesses,Diagnosis,Treatment,Gender
0,55,1,1,140,90,100,220,50% blockage in the left anterior descending ...,0,1,1,0,none,coronary artery disease (cad),"angioplasty,coronary artery bypass surgery",1
1,57,1,1,150,80,110,210,60% blockage in the right coronary artery,0,1,1,0,none,coronary artery disease (cad),"angioplasty,coronary artery bypass surgery",0
2,60,1,1,130,85,95,230,75% blockage in the left anterior descending ...,0,1,1,0,none,coronary artery disease (cad),"angioplasty,coronary artery bypass surgery",1
3,62,1,1,145,90,100,240,80% blockage in the left circumflex coronary ...,0,1,1,0,none,coronary artery disease (cad),"angioplasty,coronary artery bypass surgery",0

In [18]:
df5['Previous_illnesses'].unique()

array(['none', 'recent viral infection', 'recent chest surgery',
       'tricuspid valve replacement surgery',
       'mitral valve replacement surgery',
       'aortic valve replacement surgery'], dtype=object)

In [19]:
df5['Previous_illnesses'] = df5['Previous_illnesses'].replace(['none'], 'no serious illness')

In [20]:
df5['Previous_illnesses'].unique()

array(['no serious illness', 'recent viral infection',
       'recent chest surgery', 'tricuspid valve replacement surgery',
       'mitral valve replacement surgery',
       'aortic valve replacement surgery'], dtype=object)

In [21]:
dummies=pd.get_dummies(df5.Previous_illnesses)
dummies.head(3)

,aortic valve replacement surgery,mitral valve replacement surgery,no serious illness,recent chest surgery,recent viral infection,tricuspid valve replacement surgery
0,0,0,1,0,0,0
1,0,0,1,0,0,0
2,0,0,1,0,0,0

In [22]:
df6=pd.concat([df5,dummies],axis='columns')
df6.head()

,Age,Chest_pain,Shortness_of_breath,Systolic,Diastolic,Heart_rate,Cholesterol_level,Cardiac_CT,Diabetes,Hypertension,...,Previous_illnesses,Diagnosis,Treatment,Gender,aortic valve replacement surgery,mitral valve replacement surgery,no serious illness,recent chest surgery,recent viral infection,tricuspid valve replacement surgery
0,55,1,1,140,90,100,220,50% blockage in the left anterior descending ...,0,1,...,no serious illness,coronary artery disease (cad),"angioplasty,coronary artery bypass surgery",1,0,0,1,0,0,0
1,57,1,1,150,80,110,210,60% blockage in the right coronary artery,0,1,...,no serious illness,coronary artery disease (cad),"angioplasty,coronary artery bypass surgery",0,0,0,1,0,0,0
2,60,1,1,130,85,95,230,75% blockage in the left anterior descending ...,0,1,...,no serious illness,coronary artery disease (cad),"angioplasty,coronary artery bypass surgery",1,0,0,1,0,0,0
3,62,1,1,145,90,100,240,80% blockage in the left circumflex coronary ...,0,1,...,no serious illness,coronary artery disease (cad),"angioplasty,coronary artery bypass surgery",0,0,0,1,0,0,0
4,58,1,1,135,80,105,220,90% blockage in the right coronary artery,0,1,...,no serious illness,coronary artery disease (cad),"angioplasty,coronary artery bypass surgery",1,0,0,1,0,0,0

In [23]:
df6=df6.drop('Previous_illnesses',axis='columns')
df6.head(2)

,Age,Chest_pain,Shortness_of_breath,Systolic,Diastolic,Heart_rate,Cholesterol_level,Cardiac_CT,Diabetes,Hypertension,...,Obesity,Diagnosis,Treatment,Gender,aortic valve replacement surgery,mitral valve replacement surgery,no serious illness,recent chest surgery,recent viral infection,tricuspid valve replacement surgery
0,55,1,1,140,90,100,220,50% blockage in the left anterior descending ...,0,1,...,0,coronary artery disease (cad),"angioplasty,coronary artery bypass surgery",1,0,0,1,0,0,0
1,57,1,1,150,80,110,210,60% blockage in the right coronary artery,0,1,...,0,coronary artery disease (cad),"angioplasty,coronary artery bypass surgery",0,0,0,1,0,0,0

In [24]:
df6.columns

Index(['Age', 'Chest_pain', 'Shortness_of_breath', 'Systolic', 'Diastolic',
       'Heart_rate', 'Cholesterol_level', 'Cardiac_CT', 'Diabetes',
       'Hypertension', 'Smoking', 'Obesity', 'Diagnosis', 'Treatment',
       'Gender', 'aortic valve replacement surgery',
       'mitral valve replacement surgery', 'no serious illness',
       'recent chest surgery', 'recent viral infection',
       'tricuspid valve replacement surgery'],
      dtype='object')

In [25]:
df6['Cardiac_CT'] = df6['Cardiac_CT'].replace([' 50% dilation of the proximal aorta',
       ' 55% dilation of the proximal aorta',
       ' 60% dilation of the proximal aorta',
       ' 70% dilation of the proximal aorta',
       ' 110% dilation of the proximal aorta',
       ' 120% dilation of the proximal aorta',
       ' 130% dilation of the proximal aorta',
       ' 80% dilation of the proximal aorta',
       ' 90% dilation of the proximal aorta',
       ' 100% dilation of the proximal aorta'], '50% - 130% dilation of the proximal aorta')

In [26]:
df6['Cardiac_CT'] = df6['Cardiac_CT'].replace(['30% dilation of the infrarenal aorta',
       ' 40% dilation of the thoracoabdominal aorta',
       ' 50% dilation of the thoracoabdominal aorta',
       ' 60% dilation of the thoracoabdominal aorta',
       ' 70% dilation of the thoracoabdominal aorta',
       ' 80% dilation of the thoracoabdominal aorta',
       ' 90% dilation of the thoracoabdominal aorta'], '30% - 100% dilation of the thoracoabdominal aorta')

In [27]:
df6['Cardiac_CT'] = df6['Cardiac_CT'].replace([' 60% dilation of the thoracic aorta',
       ' 50% dilation of the thoracic aorta',
       ' 70% dilation of the thoracic aorta',
       ' 40% dilation of the thoracic aorta',
       ' 55% dilation of the thoracic aorta',
       ' 65% dilation of the thoracic aorta',
       ' 75% dilation of the thoracic aorta',
       ' 90% dilation of the thoracic aorta',
       ' 45% dilation of the thoracic aorta'], '45% - 90% dilation of the thoracic aorta')

In [28]:
df6['Cardiac_CT'] = df6['Cardiac_CT'].replace([' 40% dilation of the abdominal aorta',
       ' 50% dilation of the abdominal aorta',
       ' 30% dilation of the abdominal aorta',
       ' 60% dilation of the abdominal aorta',
       ' 70% dilation of the abdominal aorta'], '40% - 70% dilation of the abdominal aorta')

In [29]:
df6['Cardiac_CT'] = df6['Cardiac_CT'].replace([' 35% dilation of the infrarenal aorta',
       ' 25% dilation of the infrarenal aorta',
       ' 40% dilation of the infrarenal aorta',
       ' 42% dilation of the infrarenal aorta',
       ' 45% dilation of the infrarenal aorta',
       ' 38% dilation of the infrarenal aorta'], '25% - 45% dilation of the infrarenal aorta')

In [30]:
filtered_df2 = df6[df6['Cardiac_CT'].isin([' 50% blockage in the left anterior descending coronary artery',
                                           ' 75% blockage in the left anterior descending coronary artery',
                                          ' 70% blockage in the left anterior descending coronary artery',
                                          ' 60% blockage in the left main coronary artery',])]
filtered_df2

,Age,Chest_pain,Shortness_of_breath,Systolic,Diastolic,Heart_rate,Cholesterol_level,Cardiac_CT,Diabetes,Hypertension,...,Obesity,Diagnosis,Treatment,Gender,aortic valve replacement surgery,mitral valve replacement surgery,no serious illness,recent chest surgery,recent viral infection,tricuspid valve replacement surgery
0,55,1,1,140,90,100,220,50% blockage in the left anterior descending ...,0,1,...,0,coronary artery disease (cad),"angioplasty,coronary artery bypass surgery",1,0,0,1,0,0,0
2,60,1,1,130,85,95,230,75% blockage in the left anterior descending ...,0,1,...,0,coronary artery disease (cad),"angioplasty,coronary artery bypass surgery",1,0,0,1,0,0,0
5,55,1,1,150,95,110,200,70% blockage in the left anterior descending ...,1,1,...,0,coronary artery disease (cad),"angioplasty,coronary artery bypass surgery",0,0,0,1,0,0,0
6,60,1,1,145,90,110,220,50% blockage in the left anterior descending ...,0,1,...,0,coronary artery disease (cad),"angioplasty,coronary artery bypass surgery",1,0,0,1,0,0,0
8,55,1,1,130,80,110,250,60% blockage in the left main coronary artery,0,1,...,0,coronary artery disease (cad),"angioplasty,coronary artery bypass surgery",1,0,0,1,0,0,0

In [31]:
df6['Cardiac_CT'].value_counts()

none                                                             117
shows thickening of the pericardium                               14
shows pericarditis with myocarditis                               12
shows pericardial effusion and tamponade                          11
40% - 70% dilation of the abdominal aorta                         11
50% - 130% dilation of the proximal aorta                         11
30% - 100% dilation of the thoracoabdominal aorta                 10
45% - 90% dilation of the thoracic aorta                          10
shows constrictive pericarditis                                    9
25% - 45% dilation of the infrarenal aorta                         8
shows effusion in the pericardium                                  8
 moderate stenosis in the pulmonary valve                          8
 moderate stenosis in the tricuspid valve                          7
 moderate stenosis in the aortic valve                             5
 severe dysfunction of the right ventricle                         5
 severe stenosis in the aortic valve                               5
 moderate stenosis in the mitral valve                             5
 moderate restriction in the ventricular filling                   5
 severe restriction in the ventricular filling                     4
 severe stenosis in the mitral valve                               4
 severe dilatation in the left ventricle                           4
 moderate dilatation in the left ventricle                         4
 moderate dysfunction of the left ventricle                        4
 moderate regurgitation in the mitral valve                        4
 30% dilation of the infrarenal aorta                              3
 mild dysfunction of the left ventricle                            3
 severe dysfunction of the left ventricle                          3
 moderate dysfunction of the right ventricle                       3
 moderate hypertrophy in the left ventricle                        3
 severe hypertrophy in the left ventricle                          3
 mild regurgitation in the mitral valve                            3
 severe regurgitation in the mitral valve                          3
 50% blockage in the left anterior descending coronary artery      2
 70% blockage in the right coronary artery                         2
 mild dysfunction of the right ventricle                           2
 mild dilatation in the left ventricle                             2
 mild stenosis in the pulmonary valve                              2
 mild stenosis in the tricuspid valve                              2
 mild hypertrophy in the left ventricle                            2
 75% blockage in the left anterior descending coronary artery      1
 80% blockage in the left circumflex coronary artery               1
 90% blockage in the right coronary artery                         1
 70% blockage in the left anterior descending coronary artery      1
 moderate hypertrophy in the right ventricle                       1
 60% blockage in the left main coronary artery                     1
 mild stenosis in the mitral valve                                 1
 60% blockage in the right coronary artery                         1
 severe hypertrophy in the right ventricle                         1
 mild restriction in the ventricular filling                       1
 severe stenosis in the tricuspid valve                            1
Name: Cardiac_CT, dtype: int64

In [32]:
dummies1=pd.get_dummies(df6.Cardiac_CT)
dummies1.head(3)

,30% dilation of the infrarenal aorta,50% blockage in the left anterior descending coronary artery,60% blockage in the left main coronary artery,60% blockage in the right coronary artery,70% blockage in the left anterior descending coronary artery,70% blockage in the right coronary artery,75% blockage in the left anterior descending coronary artery,80% blockage in the left circumflex coronary artery,90% blockage in the right coronary artery,mild dilatation in the left ventricle,...,30% - 100% dilation of the thoracoabdominal aorta,40% - 70% dilation of the abdominal aorta,45% - 90% dilation of the thoracic aorta,50% - 130% dilation of the proximal aorta,none,shows constrictive pericarditis,shows effusion in the pericardium,shows pericardial effusion and tamponade,shows pericarditis with myocarditis,shows thickening of the pericardium
0,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [33]:
df6=pd.concat([df6,dummies1],axis='columns')
df6.head()

,Age,Chest_pain,Shortness_of_breath,Systolic,Diastolic,Heart_rate,Cholesterol_level,Cardiac_CT,Diabetes,Hypertension,...,30% - 100% dilation of the thoracoabdominal aorta,40% - 70% dilation of the abdominal aorta,45% - 90% dilation of the thoracic aorta,50% - 130% dilation of the proximal aorta,none,shows constrictive pericarditis,shows effusion in the pericardium,shows pericardial effusion and tamponade,shows pericarditis with myocarditis,shows thickening of the pericardium
0,55,1,1,140,90,100,220,50% blockage in the left anterior descending ...,0,1,...,0,0,0,0,0,0,0,0,0,0
1,57,1,1,150,80,110,210,60% blockage in the right coronary artery,0,1,...,0,0,0,0,0,0,0,0,0,0
2,60,1,1,130,85,95,230,75% blockage in the left anterior descending ...,0,1,...,0,0,0,0,0,0,0,0,0,0
3,62,1,1,145,90,100,240,80% blockage in the left circumflex coronary ...,0,1,...,0,0,0,0,0,0,0,0,0,0
4,58,1,1,135,80,105,220,90% blockage in the right coronary artery,0,1,...,0,0,0,0,0,0,0,0,0,0

In [34]:
df7=df6.drop('Cardiac_CT',axis='columns')
df7.head(2)

,Age,Chest_pain,Shortness_of_breath,Systolic,Diastolic,Heart_rate,Cholesterol_level,Diabetes,Hypertension,Smoking,...,30% - 100% dilation of the thoracoabdominal aorta,40% - 70% dilation of the abdominal aorta,45% - 90% dilation of the thoracic aorta,50% - 130% dilation of the proximal aorta,none,shows constrictive pericarditis,shows effusion in the pericardium,shows pericardial effusion and tamponade,shows pericarditis with myocarditis,shows thickening of the pericardium
0,55,1,1,140,90,100,220,0,1,1,...,0,0,0,0,0,0,0,0,0,0
1,57,1,1,150,80,110,210,0,1,1,...,0,0,0,0,0,0,0,0,0,0

In [35]:
df7.columns

Index(['Age', 'Chest_pain', 'Shortness_of_breath', 'Systolic', 'Diastolic',
       'Heart_rate', 'Cholesterol_level', 'Diabetes', 'Hypertension',
       'Smoking', 'Obesity', 'Diagnosis', 'Treatment', 'Gender',
       'aortic valve replacement surgery', 'mitral valve replacement surgery',
       'no serious illness', 'recent chest surgery', 'recent viral infection',
       'tricuspid valve replacement surgery',
       ' 30% dilation of the infrarenal aorta',
       ' 50% blockage in the left anterior descending coronary artery',
       ' 60% blockage in the left main coronary artery',
       ' 60% blockage in the right coronary artery',
       ' 70% blockage in the left anterior descending coronary artery',
       ' 70% blockage in the right coronary artery',
       ' 75% blockage in the left anterior descending coronary artery',
       ' 80% blockage in the left circumflex coronary artery',
       ' 90% blockage in the right coronary artery',
       ' mild dilatation in the left ventricle',
       ' mild dysfunction of the left ventricle',
       ' mild dysfunction of the right ventricle',
       ' mild hypertrophy in the left ventricle',
       ' mild regurgitation in the mitral valve',
       ' mild restriction in the ventricular filling',
       ' mild stenosis in the mitral valve',
       ' mild stenosis in the pulmonary valve',
       ' mild stenosis in the tricuspid valve',
       ' moderate dilatation in the left ventricle',
       ' moderate dysfunction of the left ventricle',
       ' moderate dysfunction of the right ventricle',
       ' moderate hypertrophy in the left ventricle',
       ' moderate hypertrophy in the right ventricle',
       ' moderate regurgitation in the mitral valve',
       ' moderate restriction in the ventricular filling',
       ' moderate stenosis in the aortic valve',
       ' moderate stenosis in the mitral valve',
       ' moderate stenosis in the pulmonary valve',
       ' moderate stenosis in the tricuspid valve',
       ' severe dilatation in the left ventricle',
       ' severe dysfunction of the left ventricle',
       ' severe dysfunction of the right ventricle',
       ' severe hypertrophy in the left ventricle',
       ' severe hypertrophy in the right ventricle',
       ' severe regurgitation in the mitral valve',
       ' severe restriction in the ventricular filling',
       ' severe stenosis in the aortic valve',
       ' severe stenosis in the mitral valve',
       ' severe stenosis in the tricuspid valve',
       '25% - 45% dilation of the infrarenal aorta',
       '30% - 100% dilation of the thoracoabdominal aorta',
       '40% - 70% dilation of the abdominal aorta',
       '45% - 90% dilation of the thoracic aorta',
       '50% - 130% dilation of the proximal aorta', 'none',
       'shows constrictive pericarditis', 'shows effusion in the pericardium',
       'shows pericardial effusion and tamponade',
       'shows pericarditis with myocarditis',
       'shows thickening of the pericardium'],
      dtype='object')

In [36]:
from sklearn.preprocessing import LabelEncoder

# create a LabelEncoder object
le1 = LabelEncoder()
le2 = LabelEncoder()

# encode the diagnosis column
y1_encoded = le1.fit_transform(df7['Diagnosis'])

# encode the treatment column
y2_encoded = le2.fit_transform(df7['Treatment'])

# print the encoded values
print(y1_encoded)
print(y2_encoded)

[ 8  8  8  8  8  8  8  8  8  8 13 13 13 13 13 13 13 13 13 13 14 14 14 14
 14 14 14 14 14  3  3  3  3  3  3  3  3  3  3 30 30 30 30 30 30 30 30 30
 30 20 20 20 20 20 20 20 20 20 20 14  9  9  9  9  9  9  9  9  9  9 10 10
 10 10 10 10 10 10 10 10 21 21 21 21 21 21 21 21 21 21  4  4  4  4  4  4
  4  4  4  4 27 27 27 27 27 27 27 27 27 27 28 28 28 28 28 28 28 28 28 28
  0  0  0  0  0  0  0  0  0  0  0 19 19 19 19 19 19 19 19 19 19 19 12 29
 29 29 29 29 29 29 29 29 29  2  2  2  2  2  2  2  2  2  2  2  6  7 16 16
 16 16 16 16 16 16 16 16 16 17 17 17 17 17 17 17 17 17 17 17 17  1  1  1
  1  1  1  1  1  1  1  1  1 26 26 26 26 26 26 26 26 26 26 26 26 11  5  5
  5  5  5  5  5  5  5  5  5  5 15 15 15 15 15 15 15 15 15 15 15 18 18 18
 18 18 18 18 18 18 18 18 23 23 23 23 23 23 23 23 23 23 23 24 24 24 24 24
 24 24 24 24 24 24 25 25 25 25 25 25 25 25 25 25 25 25 22 22 22 22 22 22
 22 22 22 22 22 22  6  6  6  6  6  6  6  6  6  6 12 12 12 12 12 12 12 12
 12 12 11 11 11 11 11 11 11 11 11 11  7  7  7  7  7  7  7  7  7  7]
[ 0  0  0  0  0  0  0  0  0  0 23 24 23 23 24 23 24 23 23 23 24 24 24 24
 24 24 24 24 24  1  1  1  1  1  1  1  1  1  1 45 45 45 45 45 45 45 45 45
 45 35 35 35 34 35 36 35 34 33 36 24  3  4  3  3  2  3  5  3  3  3 43 13
 18 13 21 22 18 21 18 13  2 14 14 14 14 16 17 15 16 15 12 19 20 19 19 20
 19 20 19 20  6  6  7  7  7  8  9 10 11  6 25 25 25 25 25 25 25 25 25 25
 26 26 26 26 26 26 26 26 26 26 26 27 27 27 27 27 27 27 27 27 27 27 38 25
 25 25 25 25 25 25 25 25 25 37 37 37 37 37 37 37 37 37 37 37 37 29 30 30
 30 30 30 30 30 30 30 30 30 31 31 31 31 31 31 31 31 31 31 31 31 44 44 44
 44 44 44 44 44 44 44 44 44 41 41 41 41 41 41 41 41 41 41 41 41 39 44 44
 44 44 44 44 44 44 44 44 44 44 40 40 40 40 40 40 40 40 40 40 40 42 42 42
 42 42 42 42 42 42 42 42 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28
 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 28 32 32 32 32 32 32
 32 32 32 32 32 32 37 37 37 37 37 37 37 37 37 37 38 38 38 38 38 38 38 38
 38 38 39 39 39 39 39 39 39 39 39 39 29 29 29 29 29 29 29 29 29 29]

# idhar humne label encoder ko map kar liya aur unhe json file mein store kar liya toh abb predict ki categorical value ka result easy ho gyaÂ¶

In [38]:
import json
from sklearn.preprocessing import LabelEncoder

# Create an example label encoder object
# le = LabelEncoder()
# le.fit(["red", "green", "blue", "red"])

# Get the inverse mapping
inverse_mapping_diagnose = le1.inverse_transform(range(len(le1.classes_)))

# Create the dictionary of column name to inverse mapping
column_mapping = {"diagnose": {k: v for k, v in zip(range(len(le1.classes_)), inverse_mapping_diagnose)}}

# Convert the dictionary to a JSON string
json_str = json.dumps(column_mapping)

# Write the JSON string to a file
with open("inverse_mapping_diagnose.json", "w") as f:
    f.write(json_str)

In [41]:
import json

# Read the JSON file into a Python dictionary
with open("inverse_mapping_diagnose.json", "r") as f:
    column_mapping = json.load(f)

# Get the dictionary for the "color" column --- matlab color column j humne banaya hai matlab hum isme apne 
#according col name daal skte hai
diagnose_mapping = column_mapping["diagnose"]

# Example encoded result
encoded_result = 6

# Look up the original value
original_value = diagnose_mapping[str(encoded_result)]

print("Encoded value: 6")
print("Original value:", original_value)

Encoded value: 6
Original value: chronic pericarditis

In [42]:
import json
from sklearn.preprocessing import LabelEncoder

# Create an example label encoder object
# le = LabelEncoder()
# le.fit(["red", "green", "blue", "red"])

# Get the inverse mapping
inverse_mapping_treatment = le2.inverse_transform(range(len(le2.classes_)))

# Create the dictionary of column name to inverse mapping
column_mapping = {"treatment": {k: v for k, v in zip(range(len(le2.classes_)), inverse_mapping_treatment)}}

# Convert the dictionary to a JSON string
json_str = json.dumps(column_mapping)

# Write the JSON string to a file
with open("inverse_mapping_treatment.json", "w") as f:
    f.write(json_str)

In [43]:
import json

# Read the JSON file into a Python dictionary
with open("inverse_mapping_treatment.json", "r") as f:
    column_mapping = json.load(f)

# Get the dictionary for the "color" column --- matlab color column j humne banaya hai matlab hum isme apne 
#according col name daal skte hai
treatment_mapping = column_mapping["treatment"]

# Example encoded result
encoded_result = 6

# Look up the original value
original_value = treatment_mapping[str(encoded_result)]

print("Encoded value: 6")
print("Original value:", original_value)

Encoded value: 6
Original value: heart failure medications, supportive care

# model training begins from here

In [46]:
X=df7.drop(['Diagnosis','Treatment'],axis='columns')

In [47]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

# split data into train and test sets
X_train, X_test, y_train_diagnosis, y_test_diagnosis, y_train_treatment, y_test_treatment = train_test_split(X, y1_encoded, y2_encoded, test_size=0.2, random_state=42)

# train random forest classifier for diagnosis
rfc_diagnosis = RandomForestClassifier(n_estimators=100, random_state=42)
rfc_diagnosis.fit(X_train, y_train_diagnosis)

# train random forest classifier for treatment
rfc_treatment = RandomForestClassifier(n_estimators=100, random_state=42)
rfc_treatment.fit(X_train, y_train_treatment)

RandomForestClassifier(random_state=42)

In [48]:
rfc_treatment.score(X_test,y_test_treatment)

0.6865671641791045

In [49]:
rfc_diagnosis.score(X_test,y_test_diagnosis)

0.7014925373134329

In [55]:
def predict_disease(Previous_illnesses,Cardiac_CT,Age, Chest_pain, Shortness_of_breath, Systolic, Diastolic,
       Heart_rate, Cholesterol_level, Diabetes, Hypertension, Smoking, Obesity, Gender):
    
    # Initialize x array with zeros of length equal to number of columns in X
    x = np.zeros(len(X.columns))
    
    # Find the index of Cardiac_CT and Previous_illnesses in the X.columns array
    loc_index1 = np.where(X.columns == Previous_illnesses)[0][0]
    loc_index2 = np.where(X.columns == Cardiac_CT)[0][0]
    
    # Set the corresponding feature values in the x array
    x[2] = Age
    x[3] = Chest_pain
    x[4] = Shortness_of_breath
    x[5] = Systolic
    x[6] = Diastolic
    x[7] = Heart_rate
    x[8] = Cholesterol_level
    x[9] = Diabetes
    x[10] = Hypertension
    x[11] = Smoking
    x[12] = Obesity
    x[13] = Gender
    
    # Set the values of the Cardiac_CT and Previous_illnesses features to 1
    if loc_index1>0:
        x[loc_index1]=1
    if loc_index2>0:
        x[loc_index2]=1
    
    # Use the trained random forest classifier model to predict the diagnosis
    diagnosis = rfc_diagnosis.predict([x])[0]
    treatment = rfc_treatment.predict([x])[0]
    
    
    # Example encoded result
    encoded_result1 = diagnosis
    encoded_result2 = treatment

    # Look up the original value
    original_value1 = diagnose_mapping[str(encoded_result1)]
    original_value2 = treatment_mapping[str(encoded_result2)]
    
    return original_value1,original_value2

In [56]:
predict_disease('no serious illness','25% - 45% dilation of the infrarenal aorta',65,1,1,130,80,100,220,0,1,1,0,1)

c:\users\paltu\appdata\local\programs\python\python37\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  "X does not have valid feature names, but"
c:\users\paltu\appdata\local\programs\python\python37\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  "X does not have valid feature names, but"

('infrarenal aortic aneurysm',
 'surgery is typically recommended for larger aneurysms or for those that are causing symptoms')

In [58]:
predict_disease('no serious illness','none',50,1,1,155,105,100,210,0,1,1,0,0)

c:\users\paltu\appdata\local\programs\python\python37\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  "X does not have valid feature names, but"
c:\users\paltu\appdata\local\programs\python\python37\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  "X does not have valid feature names, but"

('primary pulmonary hypertension', 'surgery, oxygen therapy')

# saving the model here

In [59]:
from joblib import dump, load

In [61]:
# save both models to a single file using joblib
dump({'diagnosis': rfc_diagnosis, 'treatment': rfc_treatment}, 'rfc_models_final.joblib')

# load the models from the file
models = load('rfc_models_final.joblib')
loaded_rfc_diagnosis = models['diagnosis']
loaded_rfc_treatment = models['treatment']

In [62]:
import json
columns={
    'data_columns':[col.lower() for col in X.columns]
}

with open("columns_final.json","w") as f:
    f.write(json.dumps(columns))


# saving models individually

In [64]:
# save both models to a single file using joblib
dump({'diagnosis': rfc_diagnosis}, 'rfc_models_diagnosis.joblib')

# load the models from the file
models = load('rfc_models_diagnosis.joblib')
loaded_rfc_diagnosis = models['diagnosis']

In [65]:
# save both models to a single file using joblib
dump({'treatment': rfc_treatment}, 'rfc_models_treatment.joblib')

# load the models from the file
models = load('rfc_models_treatment.joblib')
loaded_rfc_treatment = models['treatment']